<Project>
  <PropertyGroup>
    <Authors>anko</Authors>
    <Company>anko</Company>
    <Product>NAVA</Product>
    <Title>NAVA</Title>
    <Description>Windows desktop controller for Yamaha Extended Control compatible amplifiers.</Description>
    <Copyright>Copyright (c) 2026 anko</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/azuki2anko/NAVA</RepositoryUrl>
    <NeutralLanguage>ja-JP</NeutralLanguage>
    <VersionPrefix>0.1.0</VersionPrefix>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
